import { readFile, writeFile } from 'node:fs/promises';
const federation = (await readFile(new URL('./federation.js', import.meta.url), 'utf8')).replace(/^export /gm, '');
const worker = (await readFile(new URL('./worker.js', import.meta.url), 'utf8'))
  .replace(/^import .* from '.\/federation.js';\n/, '');
await writeFile(new URL('./counterpart-ai-backend-v1.2.0-rc.2.js', import.meta.url),
  '// Generated by node build.mjs. Source: federation.js + worker.js.\n' + federation + '\n' + worker);
console.log('Built standalone Worker module: counterpart-ai-backend-v1.2.0-rc.2.js');
